/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import engine.MechanicsNotebookEngine;
import informationwindows.DialogType;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import objectmodels.Customer;
import objectmodels.Mechanic;

/**
 *
 * @author Mark
 */
public class CustomerWindow extends javax.swing.JFrame {
    private MechanicsNotebookEngine motoGarageMechanicEngine;
    private ImageIcon imageIcon;
    private boolean updateCustomer = false;
    /**
     * Creates new form CustomerWindow
     */
    public CustomerWindow() {
        initComponents();
    }
    
    /**
     * Main constructor, used when creating Customer
     * @param incomingMotoGarageMechanicEngine 
     */
    public CustomerWindow(MechanicsNotebookEngine incomingMotoGarageMechanicEngine) {
        this.motoGarageMechanicEngine = incomingMotoGarageMechanicEngine;
        initComponents();
        this.setIcon();
        this.createOrUpdateCustomerButton.setText("Create Customer");
        this.setTitle("Create Customer");
    }
    
     /**
     * Main constructor, used when updating Customer
     * @param incomingMotoGarageMechanicEngine 
     */
    public CustomerWindow(MechanicsNotebookEngine incomingMotoGarageMechanicEngine, Customer incomingCustomer) {
        this.motoGarageMechanicEngine = incomingMotoGarageMechanicEngine;
        initComponents();
        this.setIcon();
        this.createOrUpdateCustomerButton.setText("Update Customer");
        this.setTitle("Update Customer");
        this.updateCustomer = true;
        
        this.customerFirstNameTextField.setText(incomingCustomer.getFirstName());
        this.customerMiddleNameTextField.setText(incomingCustomer.getMiddleName());
        this.customerLastNameTextField.setText(incomingCustomer.getLastName());
        this.customerDescriptionTextArea.setText(incomingCustomer.getDescription());
        if(incomingCustomer.getImageIcon()!=null){
            this.customerPictureLabel.setIcon(incomingCustomer.getImageIcon());
            this.imageIcon = incomingCustomer.getImageIcon();            
        }        
    }
    
    private void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/mechanicIcon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerInformationLabel = new javax.swing.JLabel();
        customerFirstNameLabel = new javax.swing.JLabel();
        customerMiddleNameLabel = new javax.swing.JLabel();
        customerLastNameLabel = new javax.swing.JLabel();
        customerDescriptionLabel = new javax.swing.JLabel();
        customerFirstNameTextField = new javax.swing.JTextField();
        customerMiddleNameTextField = new javax.swing.JTextField();
        customerLastNameTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerDescriptionTextArea = new javax.swing.JTextArea();
        createOrUpdateCustomerButton = new javax.swing.JButton();
        newCustomerCancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        customerPictureLabel = new javax.swing.JLabel();
        openPictureButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        customerInformationLabel.setText("Customer Information");

        customerFirstNameLabel.setText("First Name");

        customerMiddleNameLabel.setText("Middle Name");

        customerLastNameLabel.setText("Last Name");

        customerDescriptionLabel.setText("Description");

        customerDescriptionTextArea.setColumns(20);
        customerDescriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(customerDescriptionTextArea);

        createOrUpdateCustomerButton.setText("Create Customer");
        createOrUpdateCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createOrUpdateCustomerButtonActionPerformed(evt);
            }
        });

        newCustomerCancelButton.setText("Cancel");
        newCustomerCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCustomerCancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Customer Picture");

        customerPictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/noImage.png"))); // NOI18N

        openPictureButton.setText("Open Picture");
        openPictureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openPictureButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(createOrUpdateCustomerButton)
                .addGap(76, 76, 76)
                .addComponent(newCustomerCancelButton)
                .addContainerGap(216, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(customerInformationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerFirstNameLabel)
                    .addComponent(customerMiddleNameLabel)
                    .addComponent(customerLastNameLabel)
                    .addComponent(customerDescriptionLabel))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(customerFirstNameTextField)
                    .addComponent(customerMiddleNameTextField)
                    .addComponent(customerLastNameTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerPictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(openPictureButton)))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerInformationLabel)
                    .addComponent(jLabel1))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerFirstNameLabel)
                            .addComponent(customerFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerMiddleNameLabel)
                            .addComponent(customerMiddleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerLastNameLabel)
                            .addComponent(customerLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerDescriptionLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(customerPictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(openPictureButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createOrUpdateCustomerButton)
                    .addComponent(newCustomerCancelButton))
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newCustomerCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCustomerCancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_newCustomerCancelButtonActionPerformed

    private void createOrUpdateCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createOrUpdateCustomerButtonActionPerformed
        // DECIDE IF CREATING OR UPDATING CUSTOMER
        // CREATING CUSTOMER
        if(!this.updateCustomer){
        String incomingFirstName = this.customerFirstNameTextField.getText();
        String incomingMiddleInitial = this.customerMiddleNameTextField.getText();
        String incomingLastName = this.customerLastNameTextField.getText();
        String incomingDescription = this.customerDescriptionTextArea.getText();
        if(this.customerFirstNameTextField.getText().equals("") || this.customerMiddleNameTextField.getText().equals("") || this.customerLastNameTextField.getText().equals("")){
            this.motoGarageMechanicEngine.getDialogFactory().createDialogMessage(DialogType.ERROR_MESSAGE, "You must provide a first name, middle initial, and last name to create a customer!");
            return;
        }
        Customer newCustomer = new Customer(incomingFirstName,incomingMiddleInitial,incomingLastName,incomingDescription);
        if(this.imageIcon!=null){
            newCustomer.setImageIcon(imageIcon);
        }
        boolean customerCreated = this.motoGarageMechanicEngine.createNewCustomer(newCustomer);

        if(customerCreated){
            this.motoGarageMechanicEngine.getDialogFactory().createDialogMessage(DialogType.INFORMATION_MESSAGE, "Customer, " + newCustomer.toString() + ", created successfully!");
        } else{
            this.motoGarageMechanicEngine.getDialogFactory().createDialogMessage(DialogType.ERROR_MESSAGE, "Can not create a Customer with that name!");
        }
        this.dispose();
        } else if(this.updateCustomer){
            // UPDATING CUSTOMER HERE
            String incomingFirstName = this.customerFirstNameTextField.getText();
            String incomingMiddleName = this.customerMiddleNameTextField.getText();
            String incomingLastName = this.customerLastNameTextField.getText();
            String incomingDescription = this.customerDescriptionTextArea.getText();
            if(this.customerFirstNameTextField.getText().equals("") || this.customerMiddleNameTextField.getText().equals("") || this.customerLastNameTextField.getText().equals("")){
                this.motoGarageMechanicEngine.getDialogFactory().createDialogMessage(DialogType.ERROR_MESSAGE, "You must provide a first name, middle name, and last name to update a customer!");
                return;
            }
            Customer updatedCustomer = new Customer(incomingFirstName,incomingMiddleName,incomingLastName,incomingDescription);

            if(this.imageIcon!=null){
                updatedCustomer.setImageIcon(imageIcon);
            }
            System.out.println("attempting to update with " + updatedCustomer.toString());
            boolean customerUpdated = this.motoGarageMechanicEngine.updateCustomer(updatedCustomer);
            if(customerUpdated){
                this.motoGarageMechanicEngine.getDialogFactory().createDialogMessage(DialogType.INFORMATION_MESSAGE, "Customer, " + updatedCustomer.toString() + ", updated successfully!");
            } else{
                this.motoGarageMechanicEngine.getDialogFactory().createDialogMessage(DialogType.ERROR_MESSAGE, "Can not updated a Customer with that name!");
            }
            this.dispose();
        }
    }//GEN-LAST:event_createOrUpdateCustomerButtonActionPerformed

    private void openPictureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openPictureButtonActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File testFile = chooser.getSelectedFile();
        String filePath="";
        if(testFile != null){
            filePath = testFile.getAbsolutePath();
            try {
                BufferedImage myPicture=null;
                try {
                    myPicture = ImageIO.read(new File(filePath));
                } catch (IOException ex) {
                Logger.getLogger(MechanicWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
                ImageIcon icon = new ImageIcon(myPicture); 
                this.customerPictureLabel.setIcon(icon);
                // set the class imageIcon to this now for absorbtion
                this.imageIcon = icon;
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_openPictureButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createOrUpdateCustomerButton;
    private javax.swing.JLabel customerDescriptionLabel;
    private javax.swing.JTextArea customerDescriptionTextArea;
    private javax.swing.JLabel customerFirstNameLabel;
    private javax.swing.JTextField customerFirstNameTextField;
    private javax.swing.JLabel customerInformationLabel;
    private javax.swing.JLabel customerLastNameLabel;
    private javax.swing.JTextField customerLastNameTextField;
    private javax.swing.JLabel customerMiddleNameLabel;
    private javax.swing.JTextField customerMiddleNameTextField;
    private javax.swing.JLabel customerPictureLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newCustomerCancelButton;
    private javax.swing.JButton openPictureButton;
    // End of variables declaration//GEN-END:variables
}
