/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import engine.MechanicsNotebookEngine;
import informationwindows.DialogType;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import objectmodels.Vehicle;

/**
 *
 * @author Mark
 */
public class NewVehicleWindow extends javax.swing.JFrame {
    private MechanicsNotebookEngine motoGarageMechanicEngine;
    private ImageIcon imageIcon;
    
    /**
     * Creates new form NewVehicleWindow
     * NOT USED
     */
    public NewVehicleWindow() {
        initComponents();
    }
    
        /**
     * Creates new form NewVehicleWindow
     */
    public NewVehicleWindow(MechanicsNotebookEngine incomingMotoGarageMechanicEngine) {
        this.motoGarageMechanicEngine = incomingMotoGarageMechanicEngine;
        initComponents();
        this.setIcon();
    }
    
    private void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/mechanicIcon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newVehicleInformationLabel = new javax.swing.JLabel();
        createVehicleButton = new javax.swing.JButton();
        newVehicleCancelButton = new javax.swing.JButton();
        newVehicleMakeLabel = new javax.swing.JLabel();
        newVehicleModelLabel = new javax.swing.JLabel();
        newVehicleYearLabel = new javax.swing.JLabel();
        newVehicleDescriptionLabel = new javax.swing.JLabel();
        newVehicleMakeTextField = new javax.swing.JTextField();
        newVehicleModelTextField = new javax.swing.JTextField();
        newVehicleYearTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        newVehicleDescriptionTextArea = new javax.swing.JTextArea();
        odometerLabel = new javax.swing.JLabel();
        newVehicleOdometerTextField = new javax.swing.JTextField();
        vinLabel = new javax.swing.JLabel();
        newVehicleVINTextField = new javax.swing.JTextField();
        colorLabel = new javax.swing.JLabel();
        newVehicleColorTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        vehiclePictureLabel = new javax.swing.JLabel();
        openPictureButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        newVehicleInformationLabel.setText("New Vehicle Information");

        createVehicleButton.setText("Create Vehicle");
        createVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createVehicleButtonActionPerformed(evt);
            }
        });

        newVehicleCancelButton.setText("Cancel");
        newVehicleCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newVehicleCancelButtonActionPerformed(evt);
            }
        });

        newVehicleMakeLabel.setText("Make");

        newVehicleModelLabel.setText("Model");

        newVehicleYearLabel.setText("Year");

        newVehicleDescriptionLabel.setText("Description");

        newVehicleDescriptionTextArea.setColumns(20);
        newVehicleDescriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(newVehicleDescriptionTextArea);

        odometerLabel.setText("Odometer");

        vinLabel.setText("VIN");

        colorLabel.setText("Color");

        jLabel1.setText("Vehicle Picture");

        vehiclePictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/noImage.png"))); // NOI18N

        openPictureButton.setText("Open Picture");
        openPictureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openPictureButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(newVehicleModelLabel)
                                    .addComponent(newVehicleMakeLabel)
                                    .addComponent(newVehicleYearLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(colorLabel)
                                    .addComponent(vinLabel)))
                            .addComponent(odometerLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newVehicleDescriptionLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newVehicleVINTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(newVehicleInformationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(newVehicleMakeTextField)
                                .addComponent(newVehicleModelTextField)
                                .addComponent(newVehicleYearTextField))
                            .addComponent(newVehicleColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newVehicleOdometerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(createVehicleButton)
                        .addGap(39, 39, 39)
                        .addComponent(newVehicleCancelButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(openPictureButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(103, 103, 103))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(vehiclePictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(81, 81, 81)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newVehicleInformationLabel)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newVehicleMakeLabel)
                    .addComponent(newVehicleMakeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newVehicleModelLabel)
                            .addComponent(newVehicleModelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newVehicleYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newVehicleYearLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newVehicleColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colorLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vinLabel)
                            .addComponent(newVehicleVINTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(odometerLabel)
                            .addComponent(newVehicleOdometerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(newVehicleDescriptionLabel)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(vehiclePictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(openPictureButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createVehicleButton)
                            .addComponent(newVehicleCancelButton)))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newVehicleCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newVehicleCancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_newVehicleCancelButtonActionPerformed

    private void createVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createVehicleButtonActionPerformed
        // TODO add your handling code here:
        Integer newVehicleYear;
        Integer newVehicleOdometer;
        // check to ensure at least the make, model, and year are ENTERED and accurate
        String newVehicleMake = this.newVehicleMakeTextField.getText();
        String newVehicleModel = this.newVehicleModelTextField.getText();
        String newVehicleColor = this.newVehicleColorTextField.getText();
        String newVehicleVIN = this.newVehicleVINTextField.getText();
        
        String newVehicleDescription = this.newVehicleDescriptionTextArea.getText();
        // MUST HAVE AT LEAST A MAKE AND MODEL
        if(newVehicleMake.equals("")||newVehicleModel.equals("")){
            this.motoGarageMechanicEngine.getDialogFactory().createDialogMessage(DialogType.WARNING_MESSAGE, "You must specify a Make, Model and Year before creating a Vehicle!");
            //if(newVehicleYear
            return;
        }else{
            // now try the year
            try{
                newVehicleYear = Integer.parseInt(this.newVehicleYearTextField.getText());
                newVehicleOdometer = Integer.parseInt(this.newVehicleOdometerTextField.getText());
            }catch(NumberFormatException ex){
                this.motoGarageMechanicEngine.getDialogFactory().createDialogMessage(DialogType.WARNING_MESSAGE, "The Vehicle Year must be an Integer(ie 1997)!");
                return;
            }
            Vehicle newVehicle = new Vehicle(newVehicleMake,newVehicleModel,newVehicleYear,newVehicleColor, newVehicleVIN,newVehicleOdometer,newVehicleDescription);
            if(this.imageIcon!=null){
            newVehicle.setImageIcon(imageIcon);
            }
            boolean vehicleCreated = this.motoGarageMechanicEngine.createNewVehicle(newVehicle);
            if(vehicleCreated){
                this.motoGarageMechanicEngine.getDialogFactory().createDialogMessage(DialogType.INFORMATION_MESSAGE, "The Vehicle, " + newVehicle.toString() +", has been created!");
            }else{
                this.motoGarageMechanicEngine.getDialogFactory().createDialogMessage(DialogType.WARNING_MESSAGE, "The Vehicle was not created!");
            }
            this.dispose();           
        }

    }//GEN-LAST:event_createVehicleButtonActionPerformed

    private void openPictureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openPictureButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File testFile = chooser.getSelectedFile();
        String filePath="";
        if(testFile != null){
            filePath = testFile.getAbsolutePath();
            try {
                BufferedImage myPicture=null;
                try {
                    myPicture = ImageIO.read(new File(filePath));
                } catch (IOException ex) {
                Logger.getLogger(MechanicWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
                ImageIcon icon = new ImageIcon(myPicture); 
                this.vehiclePictureLabel.setIcon(icon);
                // set the class imageIcon to this now for absorbtion
                this.imageIcon = icon;
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_openPictureButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewVehicleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewVehicleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewVehicleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewVehicleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewVehicleWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel colorLabel;
    private javax.swing.JButton createVehicleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newVehicleCancelButton;
    private javax.swing.JTextField newVehicleColorTextField;
    private javax.swing.JLabel newVehicleDescriptionLabel;
    private javax.swing.JTextArea newVehicleDescriptionTextArea;
    private javax.swing.JLabel newVehicleInformationLabel;
    private javax.swing.JLabel newVehicleMakeLabel;
    private javax.swing.JTextField newVehicleMakeTextField;
    private javax.swing.JLabel newVehicleModelLabel;
    private javax.swing.JTextField newVehicleModelTextField;
    private javax.swing.JTextField newVehicleOdometerTextField;
    private javax.swing.JTextField newVehicleVINTextField;
    private javax.swing.JLabel newVehicleYearLabel;
    private javax.swing.JTextField newVehicleYearTextField;
    private javax.swing.JLabel odometerLabel;
    private javax.swing.JButton openPictureButton;
    private javax.swing.JLabel vehiclePictureLabel;
    private javax.swing.JLabel vinLabel;
    // End of variables declaration//GEN-END:variables
}
