/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import engine.MotoGarageNotebookEngine;
import informationwindows.DialogType;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import objectmodels.Vehicle;

/**
 *
 * @author Mark
 */
public class VehicleWindow extends javax.swing.JFrame {
    private MotoGarageNotebookEngine motoGarageMechanicEngine;
    private ImageIcon imageIcon;
    boolean updateVehicle = false;
    
    /**
     * Creates new form VehicleWindow
     * NOT USED
     */
    public VehicleWindow() {
        initComponents();
    }
    
    /**
     * Creates new form VehicleWindow, used for creating a Vehicle
     */
    public VehicleWindow(MotoGarageNotebookEngine incomingMotoGarageMechanicEngine) {
        this.motoGarageMechanicEngine = incomingMotoGarageMechanicEngine;
        initComponents();
        this.setIcon();
        this.createOrUpdateVehicleButton.setText("Create Vehicle");
        this.setTitle("Create Vehicle");
    }
    
    /**
     * Creates new form VehicleWindow, used for updating a Vehicle
     */
    public VehicleWindow(MotoGarageNotebookEngine incomingMotoGarageMechanicEngine,Vehicle incomingVehicle) {
        this.motoGarageMechanicEngine = incomingMotoGarageMechanicEngine;
        initComponents();
        this.setIcon();
        this.createOrUpdateVehicleButton.setText("Update Vehicle");
        this.setTitle("Update Vehicle");
        this.updateVehicle = true;
        
        this.vehicleModelTextField.setText(incomingVehicle.getModel());
        this.vehicleMakeTextField.setText(incomingVehicle.getMake());
        this.vehicleYearTextField.setText(incomingVehicle.getYear().toString());
        this.vehicleColorTextField.setText(incomingVehicle.getColor());
        this.vehicleVINTextField.setText(incomingVehicle.getVIN());
        this.vehicleOdometerTextField.setText(incomingVehicle.getOdometer().toString());
        this.vehicleDescriptionTextArea.setText(incomingVehicle.getDescription());
        if(incomingVehicle.getImageIcon()!=null){
            this.vehiclePictureLabel.setIcon(incomingVehicle.getImageIcon());
            this.imageIcon=incomingVehicle.getImageIcon();
        } 
        
    }
    
    private void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/mechanicIcon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newVehicleInformationLabel = new javax.swing.JLabel();
        createOrUpdateVehicleButton = new javax.swing.JButton();
        newVehicleCancelButton = new javax.swing.JButton();
        vehicleMakeLabel = new javax.swing.JLabel();
        vehicleModelLabel = new javax.swing.JLabel();
        vehicleYearLabel = new javax.swing.JLabel();
        vehicleDescriptionLabel = new javax.swing.JLabel();
        vehicleMakeTextField = new javax.swing.JTextField();
        vehicleModelTextField = new javax.swing.JTextField();
        vehicleYearTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        vehicleDescriptionTextArea = new javax.swing.JTextArea();
        vehicleOdometerLabel = new javax.swing.JLabel();
        vehicleOdometerTextField = new javax.swing.JTextField();
        vehicleVinLabel = new javax.swing.JLabel();
        vehicleVINTextField = new javax.swing.JTextField();
        vehicleColorLabel = new javax.swing.JLabel();
        vehicleColorTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        vehiclePictureLabel = new javax.swing.JLabel();
        openPictureButton = new javax.swing.JButton();
        clearPictureButton = new javax.swing.JButton();
        viewAndEditVehicleMaintenanceTypesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        newVehicleInformationLabel.setText("Vehicle Information");

        createOrUpdateVehicleButton.setText("Create Vehicle");
        createOrUpdateVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createOrUpdateVehicleButtonActionPerformed(evt);
            }
        });

        newVehicleCancelButton.setText("Cancel");
        newVehicleCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newVehicleCancelButtonActionPerformed(evt);
            }
        });

        vehicleMakeLabel.setText("Make");

        vehicleModelLabel.setText("Model");

        vehicleYearLabel.setText("Year");

        vehicleDescriptionLabel.setText("Description");

        vehicleDescriptionTextArea.setColumns(20);
        vehicleDescriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(vehicleDescriptionTextArea);

        vehicleOdometerLabel.setText("Odometer");

        vehicleVinLabel.setText("VIN");

        vehicleColorLabel.setText("Color");

        jLabel1.setText("Vehicle Picture");

        vehiclePictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/noImage.png"))); // NOI18N

        openPictureButton.setText("Open");
        openPictureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openPictureButtonActionPerformed(evt);
            }
        });

        clearPictureButton.setText("Clear");
        clearPictureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearPictureButtonActionPerformed(evt);
            }
        });

        viewAndEditVehicleMaintenanceTypesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vehicleMaintenanceType32x32EDIT.png"))); // NOI18N
        viewAndEditVehicleMaintenanceTypesButton.setToolTipText("View and Edit Vehicle Specific Maintenance Types");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(vehicleModelLabel)
                                    .addComponent(vehicleMakeLabel)
                                    .addComponent(vehicleYearLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vehicleColorLabel)
                                    .addComponent(vehicleVinLabel)))
                            .addComponent(vehicleOdometerLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(vehicleDescriptionLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(vehicleMakeTextField)
                            .addComponent(vehicleModelTextField)
                            .addComponent(vehicleYearTextField)
                            .addComponent(vehicleColorTextField)
                            .addComponent(vehicleVINTextField)
                            .addComponent(vehicleOdometerTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(createOrUpdateVehicleButton)
                        .addGap(39, 39, 39)
                        .addComponent(newVehicleCancelButton)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(57, 57, 57))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(openPictureButton)
                                    .addComponent(viewAndEditVehicleMaintenanceTypesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(clearPictureButton)
                                .addGap(23, 23, 23))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(vehiclePictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(newVehicleInformationLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(newVehicleInformationLabel)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleMakeLabel)
                    .addComponent(vehicleMakeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vehicleModelLabel)
                    .addComponent(vehicleModelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehicleYearLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehicleColorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleVinLabel)
                    .addComponent(vehicleVINTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleOdometerLabel)
                    .addComponent(vehicleOdometerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(vehicleDescriptionLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vehiclePictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(openPictureButton)
                            .addComponent(clearPictureButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createOrUpdateVehicleButton)
                            .addComponent(newVehicleCancelButton)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewAndEditVehicleMaintenanceTypesButton)
                        .addGap(61, 61, 61))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newVehicleCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newVehicleCancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_newVehicleCancelButtonActionPerformed

    private void createOrUpdateVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createOrUpdateVehicleButtonActionPerformed
        // TODO add your handling code here:
        Integer newVehicleYear;
        Integer newVehicleOdometer;
        // check to ensure at least the make, model, and year are ENTERED and accurate
        String newVehicleMake = this.vehicleMakeTextField.getText();
        String newVehicleModel = this.vehicleModelTextField.getText();
        String newVehicleColor = this.vehicleColorTextField.getText();
        String newVehicleVIN = this.vehicleVINTextField.getText();
        
        String newVehicleDescription = this.vehicleDescriptionTextArea.getText();
        // MUST HAVE AT LEAST A MAKE AND MODEL
        if(newVehicleMake.equals("")||newVehicleModel.equals("")){
            this.motoGarageMechanicEngine.getDialogFactory().createDialogMessage(DialogType.WARNING_MESSAGE, "You must specify a Make, Model and Year before creating a Vehicle!");
            //if(newVehicleYear
            return;
        }
        
        // now try the year
        try{
            newVehicleYear = Integer.parseInt(this.vehicleYearTextField.getText());
            newVehicleOdometer = Integer.parseInt(this.vehicleOdometerTextField.getText());
        }catch(NumberFormatException ex){
            this.motoGarageMechanicEngine.getDialogFactory().createDialogMessage(DialogType.WARNING_MESSAGE, "The Vehicle Year must be an Integer(ie 1997)!");
            return;
        }
        
        Vehicle newVehicle = new Vehicle(newVehicleMake,newVehicleModel,newVehicleYear,newVehicleColor, newVehicleVIN,newVehicleOdometer,newVehicleDescription);
        if(this.imageIcon!=null){
            newVehicle.setImageIcon(imageIcon);
        }
        // if updating...
        if(this.updateVehicle){
            boolean vehicleUpdated = this.motoGarageMechanicEngine.updateVehicle(newVehicle);
            if(vehicleUpdated){
                this.motoGarageMechanicEngine.getDialogFactory().createDialogMessage(DialogType.INFORMATION_MESSAGE, "The Vehicle, " + newVehicle.toString() +", has been updated!");
            }else{
                this.motoGarageMechanicEngine.getDialogFactory().createDialogMessage(DialogType.WARNING_MESSAGE, "The Vehicle was not updated!");
            }
            this.dispose();
        }else{ // creating...
            boolean vehicleCreated = this.motoGarageMechanicEngine.createNewVehicle(newVehicle);
            if(vehicleCreated){
                this.motoGarageMechanicEngine.getDialogFactory().createDialogMessage(DialogType.INFORMATION_MESSAGE, "The Vehicle, " + newVehicle.toString() +", has been created!");
            }else{
                this.motoGarageMechanicEngine.getDialogFactory().createDialogMessage(DialogType.WARNING_MESSAGE, "The Vehicle was not created!");
            }
            this.dispose();  
        }
          

    }//GEN-LAST:event_createOrUpdateVehicleButtonActionPerformed

    private void openPictureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openPictureButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File testFile = chooser.getSelectedFile();
        String filePath="";
        if(testFile != null){
            filePath = testFile.getAbsolutePath();
            try {
                BufferedImage myPicture=null;
                try {
                    myPicture = ImageIO.read(new File(filePath));
                } catch (IOException ex) {
                Logger.getLogger(MechanicWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
                ImageIcon icon = new ImageIcon(myPicture); 
                this.vehiclePictureLabel.setIcon(icon);
                // set the class imageIcon to this now for absorbtion
                this.imageIcon = icon;
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_openPictureButtonActionPerformed

    private void clearPictureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearPictureButtonActionPerformed
        // TODO add your handling code here:
        this.imageIcon=null;
        vehiclePictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/noImage.png"))); // NOI18N
    }//GEN-LAST:event_clearPictureButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehicleWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearPictureButton;
    private javax.swing.JButton createOrUpdateVehicleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newVehicleCancelButton;
    private javax.swing.JLabel newVehicleInformationLabel;
    private javax.swing.JButton openPictureButton;
    private javax.swing.JLabel vehicleColorLabel;
    private javax.swing.JTextField vehicleColorTextField;
    private javax.swing.JLabel vehicleDescriptionLabel;
    private javax.swing.JTextArea vehicleDescriptionTextArea;
    private javax.swing.JLabel vehicleMakeLabel;
    private javax.swing.JTextField vehicleMakeTextField;
    private javax.swing.JLabel vehicleModelLabel;
    private javax.swing.JTextField vehicleModelTextField;
    private javax.swing.JLabel vehicleOdometerLabel;
    private javax.swing.JTextField vehicleOdometerTextField;
    private javax.swing.JLabel vehiclePictureLabel;
    private javax.swing.JTextField vehicleVINTextField;
    private javax.swing.JLabel vehicleVinLabel;
    private javax.swing.JLabel vehicleYearLabel;
    private javax.swing.JTextField vehicleYearTextField;
    private javax.swing.JButton viewAndEditVehicleMaintenanceTypesButton;
    // End of variables declaration//GEN-END:variables
}
