/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import engine.MotoGarageNotebookEngine;
import informationwindows.DialogType;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;
import objectmodels.VehicleType;

/**
 *
 * @author Mark
 */

public class VehicleTypesMainWindow extends javax.swing.JDialog {
    private MotoGarageNotebookEngine motoGarageNotebookEngine;

    /**
     * Creates new form VehicleTypesMainWindow
     */
    public VehicleTypesMainWindow() {
        initComponents();
    }

         /**
     * Creates new form MaintenanceTypesMainWindow
     */
    public VehicleTypesMainWindow(java.awt.Frame parent,boolean modal,MotoGarageNotebookEngine incomingMotoGarageNotebookEngine) {
        super(parent, modal);
        this.motoGarageNotebookEngine = incomingMotoGarageNotebookEngine;
        initComponents();
        this.setIcon();
        this.setTitle("Vehicle Types");
        this.refreshVehicleTypeTable();
    }
    
    private void setIcon(){
        //setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/mechanicIcon.png")));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/MGFavicon.png")));
    }
    
        /**
     * Method used to refresh the Maintenance Type Table
     */
    public void refreshVehicleTypeTable(){
        
        DefaultTableModel model = (DefaultTableModel) vehicleTypesJTable.getModel();

        int rowCount = model.getRowCount();
        //Integer currentRowSelected = maintenanceTypesTable.getSelectedRow();
        // remove all mechanics
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        
        if(this.motoGarageNotebookEngine.getVehicleTypeArray().length>0){
            VehicleType[] vehicleTypes = this.motoGarageNotebookEngine.getVehicleTypeArray();
            int newRowCount = vehicleTypes.length;
            for (int i = 0  ; i <newRowCount ; i++) {
                Object[]VehicleTypeObject = vehicleTypes[i].getVehicleTypeObject();
                model.addRow(VehicleTypeObject);       
            }
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        vehicleTypeToolBar = new javax.swing.JToolBar();
        vehicleTypeAddButton = new javax.swing.JButton();
        vehicleTypeEditButton = new javax.swing.JButton();
        vehicleTypeDeleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vehicleTypesJTable = new javax.swing.JTable();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        vehicleTypeToolBar.setFloatable(false);
        vehicleTypeToolBar.setOrientation(javax.swing.SwingConstants.VERTICAL);
        vehicleTypeToolBar.setRollover(true);

        vehicleTypeAddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vehicleType32x32ADD.png"))); // NOI18N
        vehicleTypeAddButton.setFocusable(false);
        vehicleTypeAddButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        vehicleTypeAddButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        vehicleTypeAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleTypeAddButtonActionPerformed(evt);
            }
        });
        vehicleTypeToolBar.add(vehicleTypeAddButton);

        vehicleTypeEditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vehicleType32x32EDIT.png"))); // NOI18N
        vehicleTypeEditButton.setFocusable(false);
        vehicleTypeEditButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        vehicleTypeEditButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        vehicleTypeEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleTypeEditButtonActionPerformed(evt);
            }
        });
        vehicleTypeToolBar.add(vehicleTypeEditButton);

        vehicleTypeDeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vehicleType32x32DELETE.png"))); // NOI18N
        vehicleTypeDeleteButton.setFocusable(false);
        vehicleTypeDeleteButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        vehicleTypeDeleteButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        vehicleTypeDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleTypeDeleteButtonActionPerformed(evt);
            }
        });
        vehicleTypeToolBar.add(vehicleTypeDeleteButton);

        vehicleTypesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Make", "Model"
            }
        ));
        vehicleTypesJTable.setOpaque(true);
        vehicleTypesJTable.setFillsViewportHeight(true);
        vehicleTypesJTable.setBackground(Color.WHITE);
        jScrollPane1.setViewportView(vehicleTypesJTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vehicleTypeToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(vehicleTypeToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(closeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void vehicleTypeAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleTypeAddButtonActionPerformed
        // TODO add your handling code here:
        this.motoGarageNotebookEngine.startNewVehicleTypeWindow(this);
    }//GEN-LAST:event_vehicleTypeAddButtonActionPerformed

    private void vehicleTypeEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleTypeEditButtonActionPerformed
        // TODO add your handling code here:
        int rowSelected = this.vehicleTypesJTable.getSelectedRow();
        if(rowSelected>-1){
            VehicleType[] vehicleTypes = this.motoGarageNotebookEngine.getVehicleTypeArray();
            VehicleType selectedVehicleType = vehicleTypes[rowSelected];
            this.motoGarageNotebookEngine.startUpdateVehicleTypeWindow(this, selectedVehicleType);
        }else{
            this.motoGarageNotebookEngine.getDialogFactory().createDialogMessage(this,DialogType.INFORMATION_MESSAGE, "You need to select a Vehicle Type to edit.");
        }
        
    }//GEN-LAST:event_vehicleTypeEditButtonActionPerformed

    private void vehicleTypeDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleTypeDeleteButtonActionPerformed
        // TODO add your handling code here:
        
        int rowSelected = this.vehicleTypesJTable.getSelectedRow();

        if(rowSelected==-1){
            this.motoGarageNotebookEngine.getDialogFactory().createDialogMessage(this,DialogType.INFORMATION_MESSAGE, "You need to select a Vehicle Type to delete.");
            return;
        }
        boolean sureToDelete = this.motoGarageNotebookEngine.getDialogFactory().createConfirmMessage(this,"Are you sure you wish to delete the Vehicle Type? This is permanent!");
        if(sureToDelete){
            VehicleType[] vehicleTypes = this.motoGarageNotebookEngine.getVehicleTypeArray();
            VehicleType selectedVehicleType = vehicleTypes[rowSelected];
            if(this.motoGarageNotebookEngine.deleteVehicleType(selectedVehicleType)){
                this.motoGarageNotebookEngine.getDialogFactory().createDialogMessage(this,DialogType.INFORMATION_MESSAGE, "Vehicle Type deleted successfully!");
                this.refreshVehicleTypeTable();
            }else{
                this.motoGarageNotebookEngine.getDialogFactory().createDialogMessage(this,DialogType.ERROR_MESSAGE, "Error attempting to delete Vehicle Type! :( Please report!");
            }
//            
        }
    }//GEN-LAST:event_vehicleTypeDeleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleTypesMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleTypesMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleTypesMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleTypesMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehicleTypesMainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton vehicleTypeAddButton;
    private javax.swing.JButton vehicleTypeDeleteButton;
    private javax.swing.JButton vehicleTypeEditButton;
    private javax.swing.JToolBar vehicleTypeToolBar;
    private javax.swing.JTable vehicleTypesJTable;
    // End of variables declaration//GEN-END:variables
}
